### ISSUE TITLE
Outdated code / documentation

### ISSUE THREAD

**Issue by dorintt** [balena-io/balena-supervisor#1016]
Tried following the basic startup instructions:
```
dorin@UbuntuVM:~/balena-supervisor$ ./dindctl run --image balena/amd64-supervisor:master
Stopping dind supervisor
make: Entering directory '/home/dorin/balena-supervisor'
docker stop resinos-in-container-supervisor > /dev/null || true
Error response from daemon: No such container: resinos-in-container-supervisor
docker rm -f --volumes resinos-in-container-supervisor > /dev/null || true
Error: No such container: resinos-in-container-supervisor
make: Leaving directory '/home/dorin/balena-supervisor'
Cleaning dind supervisor volumes
Cloning into 'tools/dind/resinos-in-container'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:resin-os/resinos-in-container.git' into submodule path 'tools/dind/resinos-in-container' failed
```
I haven't worked with previous versions of balena-supervisor, so I'm trying to use it for the first time in a clean environment.

**Comment by roman-mazur** [comment]
Hi @dorintt 

Right now `dindctl` tools relies on ability to clone git repositories ([this one specifically](https://github.com/balena-os/resinos-in-container)) via SSH, and this operation fails for you.

We should probably change submodules configuration to use HTTPs for cloning, but for now, could you check if your SSH keys are [configured properly on GitHub](https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account)? If you have SSH key imported to github, this git clone operation should succeed.

**Comment by dorintt** [comment]
Thank you, indeed I did not have any ssh keys added to github for this machine.
Now the supervisor works.
