### ISSUE TITLE
$APPID should be $BALENA_APP_ID in API docs

### ISSUE THREAD

**Issue by majorz** [balena-io/balena-supervisor#1034]
User was trying to restart a container from within the same container by following the curl API examples and it did not work. It turns out our API docs use the `$APPID` environment variable, which is not existent. The correct one is `$BALENA_APP_ID`.  Example command that does not work: `curl --header "Content-Type:application/json" "$BALENA_SUPERVISOR_ADDRESS/v2/applications/$APPID/restart-service?apikey=$BALENA_SUPERVISOR_API_KEY" -d '{"serviceName": "my-service"}'`.

**Comment by xginn8** [comment]
This issue was fixed in v10.1.3 (`f2bb8a768e655513cc72a4bd286f7803745c0f07`).
