### ISSUE TITLE
Supervisor does not report initial commit/OS version/super version

### ISSUE THREAD

**Issue by chrisys** [balena-io/balena-supervisor#1075]
In some instances, on initial boot, the supervisor is not reporting current release (for preloaded devices), host OS version, supervisor version or IP addresses.

Preloaded devices are able to start their services and run correctly without the supervisor reporting this information.

This has been noticed on balenaOS v2.32.0+rev1 with supervisor v9.14.0.

![Screenshot 2019-08-28 at 23 52 07](https://user-images.githubusercontent.com/521698/63898021-32e8e000-c9ef-11e9-8725-921e08f34977.png)

**Comment by roman-mazur** [comment]
IIRC this has been fixed in newer supervisor (should be related to this patch: #1008).

**Comment by dt-rush** [comment]
This actually just occurred on `balenaOS 2.38.0+rev1, resin-supervisor 9.15.7`:

![2019-09-03_21:02:53](https://user-images.githubusercontent.com/9595728/64208480-e842ea00-ce6c-11e9-9043-b01b241a646f.png)

`systemctl restart resin-supervisor` fixed it, as expected.

**Comment by dt-rush** [comment]
... as @xginn8 points out, that's expected, as this was [fixed in 9.16.7](https://github.com/balena-io/balena-supervisor/blob/master/CHANGELOG.md#9167---2019-06-20)

**Comment by roman-mazur** [comment]
So I believe this can be closed. Shall we, @CameronDiver ?

**Comment by CameronDiver** [comment]
Yep, this is now fixed. Thanks for the heads up.
