### ISSUE TITLE
stop_signal (SIGTERM) is not sent to old container after livepush

### ISSUE THREAD

**Issue by adipascu** [balena-io/balena-supervisor#1079]
I am doing local development, I deploy my code using `balena push xxxx.local`.
After each new push, the old container does not receive SIGTERM, this causes code that does GPU memory allocation to leak.

Here are some examples written in node.js .
```js
setInterval(Function.prototype, 1000); // keep app open
process.on('SIGTERM', () => {
  console.log("Received SIGTERM"); // <- This is not executed
  process.exit(0);
});
```
Here is an example that leaks using the `pigpio` library, it relies on SIGTERM internally to do cleanup.
```js
setInterval(Function.prototype, 1000); // keep app open
try {
  require('fs').unlinkSync('/var/run/pigpio.pid');
  console.warn('Cleaned up previous pigpio lock file, we leaked memory in a previous container :(');
} catch (e) {
  // Should to fail, lock file should not exist
}
const { Gpio } = require('pigpio');
new Gpio(18, { mode: Gpio.OUTPUT }).digitalWrite(false);
```

**Comment by CameronDiver** [comment]
So I think the reason that this is occurring is that livepush sends a `SIGKILL` by default, to speed up the restart process. It sounds like we need a method of specifying whether we kill directly, or follow the standard docker process of sending `SIGTERM` and then killing if the container does not reply after a set amount of time.

**Comment by CameronDiver** [comment]
I've created an issue on the livepush repo here to track this: https://github.com/balena-io-modules/livepush/issues/49
