### ISSUE TITLE
Add support for container contracts

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#1086]
This will allow users to define a set of requirements for their containers, which the supervisor will respect, for example `os: >= 2.38`.

These should be provided by the api (or the cli in local mode), and if any of the contracts fail to be resolved, the release will not run.

As a further extension to this, we can move towards the concept of optional containers, controlled by a contract which states in which situation the container should run.

**Comment by roman-mazur** [comment]
If requirements cannot be fulfilled, will the image download or container start be prevented?

**Comment by CameronDiver** [comment]
Currently the image download, but we're looking at extending the behaviour choices. For the first implementation, the entire release download will be blocked, and the previous release will continue to run.

**Comment by CameronDiver** [comment]
Re-opening while we also implement the l4t handling.
