### ISSUE TITLE
supervisor tried to use the api key to send logs before actually registering the device with the api key

### ISSUE THREAD

**Issue by floion** [balena-io/balena-supervisor#1189]
Observed when trying to do a self served update in staging on a rpi4 from 2.41.0+rev4 to 2.47.0+rev1:

> [INFO] Deploying /mnt/boot/config.txt...file blacklisted. Ignoring.
[INFO] Deploying /mnt/boot/start4.elf... overwriting modified file... done.
[INFO] Deploying /mnt/boot/resin-image... done.
[INFO] Deploying /mnt/boot/bcm2835-bootfiles-20190828.stamp... new file... done.
[INFO] Deploying /mnt/boot/pieeprom-latest-stable.bin... new file... done.
[INFO] Deploying /mnt/boot/device-type.json... overwriting modified file... done.
[INFO] Deploying /mnt/boot/bcm2711-rpi-4-b.dtb... done.
[INFO] Deploying /mnt/boot/config.json...file blacklisted. Ignoring.
[INFO] Deploying /mnt/boot/fixup4cd.dat... overwriting modified file... done.
[INFO] Running rollback hook 
VL805 FW version: 000137ab
[INFO] vl805 firmware update is not necessary
[INFO] Switching uboot root partition index to 3...... done.
New hooks ran successfully.
[000000060][LOG]Supervisor update start...
[000000060][LOG]No explicit supervisor version was provided, update to default version in target resinOS...
[000000062][LOG]Extracted default version is v10.6.27...
[000000063][LOG]Supervisor update: will be upgrading from v10.2.2 to v10.6.27
[000000063][LOG]Extracted supervisor vars: ID: 6175
[000000063][LOG]Setting supervisor version in the API...
[000000064][LOG]Running supervisor updater...
[000000090][LOG]Stopping supervisor and related services...
parse error: Invalid numeric literal at EOF at line 1, column 12

Following are quotes from Page:

> This caused the api to consider that api key to have no permissions for 5 minutes, and then when tried to hup during that period and it failed because the api key you were making requests with wasn't considered to have permissions to make them. It looks like https://github.com/balena-io/balena-supervisor/commit/37945b4aa5325dba3b17aec19075f87b9ca9d20e didn't fix trying to post the log-stream before provisioning at all

> The device is provisioned as part of apiBinder.start() called in https://github.com/balena-io/balena-supervisor/blob/v10.6.33/src/supervisor.ts#L121 but the logger is initialized before it in https://github.com/balena-io/balena-supervisor/blob/v10.6.33/src/supervisor.ts#L94-L98

> And as long as a uuid and deviceApi key are passed it assigns the fields and considers itself initialized fully and will try to communicate with the api: https://github.com/balena-io/balena-supervisor/blob/v10.6.33/src/logging/balena-backend.ts#L43-L45

> The thing is the config module is initialized before that in https://github.com/balena-io/balena-supervisor/blob/v10.6.33/src/supervisor.ts#L79 and will generateRequiredFields in https://github.com/balena-io/balena-supervisor/blob/v10.6.33/src/config/index.ts#L59-L61 which will create and save a uuid and deviceApiKey but not actually register them, meaning the logging module will always think it's been provisioned/initialized when it in fact has not.

**Comment by richbayliss** [comment]
I'll tackle this one, if it's a case of not logging until the device is registered 👍

**Comment by CameronDiver** [comment]
Closed by: https://github.com/balena-io/balena-supervisor/pull/1190
