### ISSUE TITLE
udev rules not fired in privleged multi-container apps

### ISSUE THREAD

**Issue by acostach** [balena-io/balena-supervisor#1200]
With single apps, enabling UDEV=1 in the dockerfile will have container udev rules fire when plugging & unplugging devices.

However, if the same service is integrated intro a multi container app, although privileged, udev rules do not fire anymore.

This occurs regardless of device type. Reproduced on jetson, up board, etc.
Example app: https://github.com/acostach/x11-nvidia

In container, run:
`$ udevadm monitor | grep UDEV`

One sample use-case where these are useful is when using X, as it relies on udev for detecting keyboards & mice.

**Comment by richbayliss** [comment]
Confirmed to be user error; it's not obvious, but `udevadm monitor` requires the host networking to work. Single container apps always run this way, but multicontainer apps do not. Forcing the multicontainer apps to host networking resolved it.
