### ISSUE TITLE
Initial application download stalls at 99% if local mode enabled during download

### ISSUE THREAD

**Issue by chrisys** [balena-io/balena-supervisor#1201]
Add a new device (in this case tested with Pi 3) to an application that already has a release. The device begins to download the release. Switch the device into local mode, the device gets to 99% updating status and does not complete.

If you then switch the device back out of local mode the download completes.

![Screenshot 2020-02-10 at 15 00 27](https://user-images.githubusercontent.com/521698/74160945-14ca1180-4c16-11ea-87d8-4e995d61cd68.png)

**Comment by CameronDiver** [comment]
@chrisys This isn't strictly a supervisor issue - the supervisor won't update it's download progress on with the api whilst in local mode, and the last known download progress will be shown by the dashboard. I think the dashboard should be responsible for not showing download progress when in local mode.

I've made an issue here to track it: https://github.com/balena-io/balenacloud-dashboard/issues/3462 and I'm going to close this one - thanks for the report!
