### ISSUE TITLE
Allow of switching usb/pcie lanes configuration for jetson-tx2

### ISSUE THREAD

**Issue by acostach** [balena-io/balena-supervisor#1206]
The number of usb3.0 and pcie ports and lane configurations
can be achieved by modifying odmdata on the Jetson TX2. It is
stored in /dev/mmcblk0boot0 partition and may be modified by switching
a few bytes at their respective offsets. Configurations available are from #1 to #6, and are detailed
at https://developer.download.nvidia.com/embedded/L4T/r32-2_Release_v1.0/Tegra_Linux_Driver_Package_TX2_Adaptation_Guide.pdf?tRAE1_pdRdYFmDI0YEUiMDTmSTnMec2wUNfUmSrBroHGBOUcF1W9rEEJ1oSmku8X7mBQEv7pO4x5Uc8cKCyd-BwIovHrqVq-_CX8nu9QcZlt_WRw3_iJ2lQG1o8OrlEqobqWGFEpDH_iUK5yVh4FYHdtmOzkXG7FXxvnXqkibS_IsBNrvvNMCu8-p8cqP4IJzMw
pages 13-14.

For instance,  switching to 'Configuration #2' with value 0x1090000 will allow one USB3.0 port on uphy lane 0.

Supervisor will read the existing configuration and alter it on the device at the specified
offsets in the mmcblk0boot0 partition.

This feature is intended for now solely for the Jetson TX2 and derivate device types.

HQ: https://github.com/balena-io/balena/issues/2166

**Comment by AeroNotix** [comment]
There are still use-cases where different device-tree settings are needed for custom carrier boards in addition to ODMDATA values. Is there any feature/method you are planning on adding which could account for this?

**Comment by AeroNotix** [comment]
What about adding in additional firmware? There are still use-cases I am not sure are entirely covered by just being able to set the odmdata+custom device tree.

**Comment by acostach** [comment]
@AeroNotix if additional firmware needs to be added in the hostOS and firmware's license allows, we can install that in the base tx2 image directly. Otherwise it can be added by the APP in container.

**Comment by 20k-ultra** [comment]
The device configuration value the dashboard will pass to the Supervisor is `RESIN_HOST_CONFIG_odmdata_configuration`. The value of this configuration will just be an integer mapping to a configuration. For example, Configuration 1 will return value of 1.

```js
{
RESIN_HOST_CONFIG_odmdata_configuration: 1, // Configuration #1
RESIN_HOST_CONFIG_odmdata_configuration: 2, // Configuration #2
RESIN_HOST_CONFIG_odmdata_configuration: 3, // Configuration #3
RESIN_HOST_CONFIG_odmdata_configuration: 4, // Configuration #4
RESIN_HOST_CONFIG_odmdata_configuration: 5, // Configuration #5
RESIN_HOST_CONFIG_odmdata_configuration: 6, // Configuration #6
}
```

**Comment by 20k-ultra** [comment]
Added in v11.13.0.
