### ISSUE TITLE
Move misleading log message

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1277]
The [applyListeningRules](https://github.com/balena-io/balena-supervisor/blob/40f7ba6b2f603131975eb87f8c6f2f5bdd57b5b8/src/supervisor-api.ts#L197) function's catch block logs "stopping API". 

https://github.com/balena-io/balena-supervisor/blob/40f7ba6b2f603131975eb87f8c6f2f5bdd57b5b8/src/supervisor-api.ts#L202-L216

This is misleading since 

https://github.com/balena-io/balena-supervisor/blob/40f7ba6b2f603131975eb87f8c6f2f5bdd57b5b8/src/supervisor-api.ts#L219-L223

is what performs that action and within that function it only stops the service if the server is not null. 

Since the function that calls applyListeningRules is before the server value being set it always returns null therefore not actually stopping the server despite the log saying the API is being stopped.

I purpose that the "stopping API." section simply be moved to the stop function.

**Comment by CameronDiver** [comment]
It's better to report that we're not starting up the API. This has happened in the past, before these logs existed, and users had no idea why the supervisor wasn't responding to endpoints. Definitely the wording could be clearer, but let's make sure users know what's going on.
