### ISSUE TITLE
Dbus error when updating while openvpn-resin.service is not available on host

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1293]
**UPDATE**: I have been able to create reproducible steps to get this state to occur as well as I have defined a scope of what's impacted and how it's resolved until the device gets back into the same state. I've yet to figure out what the problem actually is though and what service is responsible but one thing for certain is that it has so far only happened on Supervisor v11.2.0 regardless of balenaOS and where it was provisioned from (production or BoB).

**environment:**
 Supervisor v11.2.0
 balenaOS 2020.04.0 (from production) and balenaOS 2.47.0+rev1 (from BoB)

**Steps to reproduce:**
Provision a device then SSH to it and run `update-resin-supervisor -t v11.2.0` then do the following:

-  reboot the device either by SSHing to it or via API call
OR
- shutting down the device by SSHing to it or via API call then turning it back on

**How to verify you're in the broken state:**

1. SSH to the machine and observe docker container logs from supervisor. You will see the error message related to Dbus 
2. You can also use one of the endpoints that appear to be affected listed below

Examples of logs:

```sh
[error]   Error on POST /v2/applications/1/purge:  Error: Unit openvpn-resin.service not loaded.
[error]         at new DBusError (/usr/src/app/node_modules/dbus/lib/error.js:9:9)
[error]       at createError (/usr/src/app/node_modules/dbus/lib/bus.js:243:9)

[error]   Scheduling another update attempt in 64000ms due to failure:  Error: Unit openvpn-resin.service not loaded.
[error]         at new DBusError (/usr/src/app/node_modules/dbus/lib/error.js:9:9)
[error]       at createError (/usr/src/app/node_modules/dbus/lib/bus.js:243:9)

[error]   Device state apply error Error: Unit openvpn-resin.service not loaded.
[error]         at new DBusError (/usr/src/app/node_modules/dbus/lib/error.js:9:9)
[error]       at createError (/usr/src/app/node_modules/dbus/lib/bus.js:243:9)
```

**Effects of issue:**

Some endpoints are affected and others aren't. The affected endpoints will throw an exception with the dbus error and respond with a 503.

**Affected areas:**

From the example logs above we can see Device state apply functionality and update scheduler is throwing the Dbus exception.

The following endpoints will error with 503 and log the Dbus exception.

- [POST /v1/purge](https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1purge) 
- [POST /v1/restart](https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1restart)
- [POST /v2/applications/:appId/restart](https://www.balena.io/docs/reference/supervisor/supervisor-api/#restart-all-services-in-an-application-post-v2applicationsappidrestart) _Interesting that restart is affected but restart-service endpoint is not_
- [POST /v2/applications/:appId/purge](https://www.balena.io/docs/reference/supervisor/supervisor-api/#purge-an-application-data-post-v2applicationsappidpurge)

It's very interesting that the same v1 and v2 endpoints are affected. This is something to continue to look into as it might lead to the issue.

**Does it auto resolve ?**
You will continue to see these errors until you restart the openvpn-resin.service on the host. I did that with `systemctl restart openvpn-resin.service` then hitting one of the affected endpoints above will work.

**Does this happen in a non-BoB provisioned device?**
This did not happen on a device provisioned from production. However this was also running different versions: supervisor v10.8.0 and balenaOS 2020.04.0 so it might not be BoB specific.

I tested another BoB provisioned device running supervisor v10.6.27 and balenaOS 2.47.0+rev1 and it did not have this dbus error.

---
**This part is the original issue content that I'm leaving but it's really outdated and confusing. The update contains all relevant info.**

[Chaos engineering](https://en.wikipedia.org/wiki/Chaos_engineering) exercise here...when I was testing all the API endpoints one of them was [POST /v1/update](https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1update). After hitting that endpoint I saw the following log:

```sh
[error]   Scheduling another update attempt in 512000ms due to failure:  Error: Unit openvpn-resin.service not loaded.
[error]         at new DBusError (/usr/src/app/node_modules/dbus/lib/error.js:9:9)
[error]       at createError (/usr/src/app/node_modules/dbus/lib/bus.js:243:9)
[error]   Device state apply error Error: Unit openvpn-resin.service not loaded.
[error]         at new DBusError (/usr/src/app/node_modules/dbus/lib/error.js:9:9)
[error]       at createError (/usr/src/app/node_modules/dbus/lib/bus.js:243:9)
```

It's important to note that my Pi4 is provisioned with BoB so there may just be a a configuration setting I have wrong however I will like to investigate this some more. I exit the supervisor and on the host I check the status of openvpn-resin.service and it was running as seen here:

![image](https://user-images.githubusercontent.com/3946250/81089473-6b1fb700-8eca-11ea-8c9e-e2623db80e8c.png)

After restarting the openvpn-resin.service and hitting the /v1/update endpoint again there was no error.

What happened that caused the dbus error ? 

My theory is because my device is configured to talk to BoB with mDNS domain of which is failing to resolve then this error occurs. Info on that issue can be found at https://github.com/balena-io/balena-supervisor/issues/1291. 

I realize restarting the openvpn service would not fix the mDNS issue but that's what I experienced and all the info I have as of right now.

**Comment by CameronDiver** [comment]
@20k-ultra did this auto-resolve, or did you resolve it by restarting the service? This is important because it's a high priority item if it did not auto-resolve.

**Comment by 20k-ultra** [comment]
I was doing a lot of things at the time to run threw all the tests. My memory of the timeline was I hit update endpoint and saw the dbus error. I checked status of that service and it was running (seen in screenshot above). I restarted the service just to see if that exponential backoff request would go away and it appeared to have gone away after restarting. So it does sound like it wasn't auto-resolve but that might just have been coincidence with my timing.

I will try to reproduce and confirm behaviour.

**Comment by 20k-ultra** [comment]
I can't confirm but all the error messages are the same exception wether it's an affected API call, state change, or update it's always `Error: Unit openvpn-resin.service not loaded.`. I think then if we fix it once it will resolve it everywhere.

After posting the update I began to trace where the exception is coming from. The exception is originated from the systemd.GetUnit function: https://github.com/balena-io/balena-supervisor/blob/313ee2048aeaf2cbe4fd9808e037474201afae4f/src/lib/dbus.ts#L103-L109
