### ISSUE TITLE
V1 Start/Restart app with invalid appId throws exception

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1297]
If I try to start or restart an app via the API using [POST /v1/restart](https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1restart) or the start variant will return 503. This is because the supervisor API throws an exception and haproxy returns 503 since it is unavailable.

The API is throwing an exception because it cannot find the app provided in this purposely incorrectly request. In the V2 API this situation is handled more gracefully and a 404 is returned when trying to restart an unknown service/app..

```sh
curl -X POST --header "Content-Type:application/json" \ 
    --data '{"appId": 5}' \
    "$BALENA_SUPERVISOR_ADDRESS/v1/restart?apikey=$BALENA_SUPERVISOR_API_KEY"
{"status":"failed","message":"Cannot read property 'services' of undefined"}
```

**Comment by CameronDiver** [comment]
Looks like the same issue as https://github.com/balena-io/balena-supervisor/issues/1299
