### ISSUE TITLE
No rule to make target 'stop-supervisor'.  Stop.

### ISSUE THREAD

**Issue by Robokishan** [balena-io/balena-supervisor#1306]
when i am running this command according to the readme.md in my ubuntu machine 
./dindctl run --image balena/amd64-supervisor:master --preload

i am having an error 
Stopping dind supervisor
make: Entering directory '/home/oizom/Documents/balena-supervisor'
make: *** No rule to make target 'stop-supervisor'.  Stop.
make: Leaving directory '/home/oizom/Documents/balena-supervisor'
can you be specific and update the documentation regarding balena-supervisor build and running

**Comment by CameronDiver** [comment]
Ah, this was missed in a refactor of the documentation and entire testing process. I've updated the scripts here: https://github.com/balena-io/balena-supervisor/pull/1307

**Comment by Robokishan** [comment]
I am trying to run balena supervisor in balena-engine. can you provide any documents to run balena-supervisor  ?

**Comment by CameronDiver** [comment]
You can, if you follow the documentation in the README (and use the above branch, or wait until it gets merged) it should be all up and running for you. Please let me know if this is not the case.

**Comment by Robokishan** [comment]
it is running thanks. 
can i use [https://hub.docker.com/r/balena/armv7hf-supervisor](https://hub.docker.com/r/balena/armv7hf-supervisor) image directly

**Comment by CameronDiver** [comment]
@Robokishan by far the easiest method of developing with the supervisor is a real device, do you have a raspberry pi or something else to hand?

Otherwise if you post the output of `./dindctl logs -f -n 100` I can perhaps help you get to the bottom of things. Please also post your creation command, and confirm that you're providing a config.json from an application that you own.

**Comment by Robokishan** [comment]
Hey i am getting this kind of errors
./dindctl logs -f -n 100
-- Logs begin at Tue 2020-05-12 05:42:11 UTC. --
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 0, Code: 0, Value: 0
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 2, Code: 0, Value: -6
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 2, Code: 1, Value: 1
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 0, Code: 0, Value: 0
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 2, Code: 0, Value: -5
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 2, Code: 1, Value: 2
May 12 05:43:01 b2d7d4dbf179 kernel: evbug: Event. Dev: input21, Type: 0, Code: 0, Value: 0

**Comment by CameronDiver** [comment]
@Robokishan that means that your config.json has not been correctly added to the volume. Can you share the command you used to create the container?

**Comment by Robokishan** [comment]
@CameronDiver  Ok thanks. i tried to manually copy config.json to /mnt/boot/config.json and now My computer is connected to the balena cloud. There are couple of things that is not working i have attached screenshot here. public ip is not working and also terminal is not for my host os it is from the container's shell.

I have imx6ull board which has docker and balena-engine both installed and successfully running what i am trying to figure out is how can i run balena-supervisor so that i can connect it to cloud and push contaners from balena-cli to my board.

![balena_public_ip_query](https://user-images.githubusercontent.com/13694097/81776608-be1ded80-950c-11ea-9545-e3b75fd389b5.png)

Thanks for your great support @CameronDiver

**Comment by Robokishan** [comment]
On the pc i tried to run following commands

1. ./dindctl run --image balena/amd64-supervisor:master;./dindctl logs -f -n 100
2. sudo cp tools/dind/config.json /var/lib/docker/volumes/balena_boot_volume/_data [ i have to manually copy config.json then it was start working ]

**Comment by CameronDiver** [comment]
@Robokishan Am I reading right that you would just like to run balena-supervisor on your imx6 board, and have it show up on the dashboard? If that's the case, we're going the complete wrong way about this. I'd strongly recommend checking the [getting started guide](https://www.balena.io/os/docs/imx6ul-var-dart/getting-started/). 

If this isn't what you're trying to do, please specify exactly what the intended outcome is and I'll be able to help a bit more.

**Comment by Robokishan** [comment]
@CameronDiver  Hey yes i am trying to install balena-supervisor in my imx6 board. i saw getting-started guide but the documentation doesn't help much. so i manually installed balena-engine in board. i am just one step away which is connecting my board to cloud through balena-engine or docker doesn't matter. but i don't know where to look for such documentation. 


and looking at the https://www.balena.io/docs/reference/OS/overview/2.x/#balenaos-components 
it seems like only one missing of puzzle is balena-supervisor

**Comment by CameronDiver** [comment]
@Robokishan Unfortunately you can't just add balenaOS components and have the supervisor work, it requires a specific setup which balenaOS provides and I'm not really able provide support on how to do this as it's quite complex and you'd essentially be trying to recreate balenaOS.

I strongly recommend flashing balenaOS to your device, which will set everything up (including the supervisor). If the getting started guide isn't helping I'd encourage you to search in the [forums](https://forums.balena.io) or create a new thread and somebody will be more than happy to work through this with you.

**Comment by Robokishan** [comment]
i am not trying to re create balena-os. i tried previously to follow tutorial . but there are so many things which are not docmented. Is there any way that i can just use meta-balena-common and install all the required tools to run supervisor ?
Because there are very least devices supported with balena. and which are supported have no bunch of feature.

**Comment by Robokishan** [comment]
@CameronDiver  so i started  getting-started guide again. all the things are compiling perfectly but i am getting error in docker-disk. and the log file has nothing. so is there any guide for how to do it properly

**Comment by CameronDiver** [comment]
@Robokishan please make an issue on the [forums](https://forums.balena.io/) if you're continuing to hit issues.

**Comment by Robokishan** [comment]
Sure thank you for the support but i give up on supervisor
