### ISSUE TITLE
Add more tests for V1 HTTP endpoints

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1327]
Tests for V1 HTTP endpoints can be added here

https://github.com/balena-io/balena-supervisor/blob/9c1110af32903f0ecbdaa18ba80e64adce19402a/test/21-supervisor-api.spec.ts#L58-L60

V1 Endpoints to write tests for:

- [x] POST /V1/reboot
- [ ] GET/V1/device/host-config
- [ ] PATCH /V1/device/host-config
- [x] POST /V1/shutdown
- [x] GET /V1/device
- [x] GET /V1/healthy
- [ ] POST /V1/blink
- [ ] POST /V1/regenerate-api-key
- [x] POST /V1/restart
- [x] POST /V1/apps/:appId/stop
- [x] POST /V1/apps/:appId/start
- [x] GET /V1/apps/:appId
- [x] POST /V1/update
- [ ] POST /V1/purge

**Comment by 20k-ultra** [comment]
@pipex regarding the other issues with /v1/ endpoints we could chip away at some tests on those endpoints.

**Comment by cywang117** [comment]
All the v1 endpoints should have sufficient testing with https://github.com/balena-io/balena-supervisor/pull/1589. Closing issue 🎉
