### ISSUE TITLE
Add ability to toggle host firewall with a configuration variable

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#1353]
The firewall does not yet exist, but when it does, we'll have a variable `BALENA_HOST_FIREWALL`, which can be used to toggle the behaviour.

**Comment by richbayliss** [comment]
This is done, and merged. Use `v11.9.6` onwards.

**Comment by cywang117** [comment]
For clarity, Supervisor v11.9.1 onwards has this config var.
