### ISSUE TITLE
Allow BALENA_HOST_BOOT_SPLASH to accept a Base64 PNG image and write out to `/mnt/boot/splash/resin-logo.png`

### ISSUE THREAD

**Issue by richbayliss** [balena-io/balena-supervisor#1360]
The goal is to allow a user to specify the a PNG image to be shown at boot, from a host config variable.

- The config var name is not final
- This will be needed for Etcher Pro

**Comment by thgreasi** [comment]
HQ: https://github.com/balena-io/balena-io/issues/1972
