### ISSUE TITLE
Allow 'not' or negative operator for device type contracts

### ISSUE THREAD

**Issue by chrisys** [balena-io/balena-supervisor#1388]
When utilising the `hw.device-type` contract type, a common use case is to exclude particular device types, preventing the container running on that device type, as opposed to specifying the device type that the container *can* run on.

For example, to prevent specific services on running on devices that don't have enough memory, the Raspberry Pi Zero for example, we'd like to be able to exclude that one device but still permit all others without explicitly stating them.

**Comment by tmigone** [comment]
Also would be nice to have 'or' operator for similar reasons.

**Comment by CameronDiver** [comment]
This would actually be handled in contrato, so I've added an issue here: https://github.com/balena-io/contrato/issues/20 - maybe we can see if @jviotti thinks he would get time to work on it?
