### ISSUE TITLE
required modules for the firewall functionality need to be PRed to meta-balena

### ISSUE THREAD

**Issue by floion** [balena-io/balena-supervisor#1393]

**Comment by 20k-ultra** [comment]
https://github.com/balena-os/meta-balena/pull/1947 closed this issue.

**Comment by 20k-ultra** [comment]
Sorry was switching between too many repos...incorrectly closed this Supervisor issue when I meant to close meta-balena issue.

**Comment by alexgg** [comment]
@richbayliss @20k-ultra can this be closed? AFAIK, the firewall functionality has already been released in meta-balena. Just asking cause I have a linked issue in meta-balena I'd like to close https://github.com/balena-os/meta-balena/issues/1946
