### ISSUE TITLE
Error reporting initial configuration, will retry StatusError: "device" and "name" must be unique.

### ISSUE THREAD

**Issue by floion** [balena-io/balena-supervisor#1394]
Seen on rpi4 at version 2.52.5+rev1

Steps to reproduce:
- download 2.52.5+rev1 for rpi4 from staging
- write with dd the image to SD card
- mount the first partition of the SD card and replace it's config.json with a config.json from a production rpi4 app
- boot the board

> root@2a43cdb:~# journalctl --no-pager -u resin-supervisor
-- Logs begin at Fri 2020-07-10 06:46:25 UTC, end at Mon 2020-07-13 10:54:20 UTC. --
Jul 12 21:25:18 2a43cdb resin-supervisor[1593]: Error response from daemon: No such container: resin_supervisor
Jul 12 21:25:18 2a43cdb resin-supervisor[1616]: active
Jul 12 21:25:19 2a43cdb resin-supervisor[1617]: Error: No such object: resin_supervisor
Jul 12 21:25:19 2a43cdb resin-supervisor[1617]: Error: No such container: resin_supervisor
Jul 12 21:25:24 2a43cdb resin-supervisor[1617]: [info]    Supervisor v11.9.3 starting up...
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Setting host to discoverable
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Starting logging infrastructure
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [warn]    Invalid firewall mode: . Reverting to state: off
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    🔥 Applying firewall mode: off
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Starting firewall
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [success] 🔥 Firewall mode applied
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Starting api binder
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [event]   Event: Supervisor start {}
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Performing database cleanup for container log timestamps
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Previous engine snapshot was not stored. Skipping cleanup.
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Handling of local mode switch is completed
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Connectivity check enabled: true
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Starting periodic check for IP addresses
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Reporting initial state, supervisor version and API info
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Attempting to load any preloaded applications
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Waiting for connectivity...
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Starting API server
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Supervisor API successfully started on port 48484
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    Applying target state
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [debug]   Ensuring device is provisioned
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [event]   Event: Device bootstrap {}
Jul 12 21:25:25 2a43cdb resin-supervisor[1617]: [info]    New device detected. Provisioning...
Jul 12 21:25:26 2a43cdb resin-supervisor[1617]: [debug]   Creating supervisor0 network
Jul 12 21:25:33 2a43cdb resin-supervisor[1617]: [error]   LogBackend: server responded with status code: 401
Jul 13 08:58:25 2a43cdb resin-supervisor[1617]: [event]   Event: Device bootstrap success {}
Jul 13 08:58:25 2a43cdb resin-supervisor[1617]: [info]    Reporting initial configuration
Jul 13 08:58:25 2a43cdb resin-supervisor[1617]: [error]   Error from the API: 401
Jul 13 08:58:25 2a43cdb resin-supervisor[1617]: [error]   Error reporting initial configuration, will retry Error: Error from the API: 401
Jul 13 08:58:25 2a43cdb resin-supervisor[1617]: [error]         at /usr/src/app/dist/app.js:6:1619932
Jul 13 08:58:25 2a43cdb resin-supervisor[1617]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 13 08:58:29 2a43cdb resin-supervisor[1970]: resin_supervisor
Jul 13 08:58:29 2a43cdb systemd[1]: resin-supervisor.service: Main process exited, code=killed, status=15/TERM
Jul 13 08:58:30 2a43cdb resin-supervisor[2056]: resin_supervisor
Jul 13 08:58:30 2a43cdb resin-supervisor[2065]: active
Jul 13 08:58:32 2a43cdb resin-supervisor[2066]: Container config has not changed
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Supervisor v11.9.3 starting up...
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Setting host to discoverable
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [warn]    Invalid firewall mode: . Reverting to state: off
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    🔥 Applying firewall mode: off
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Starting logging infrastructure
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Starting firewall
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [success] 🔥 Firewall mode applied
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Starting api binder
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [event]   Event: Supervisor start {}
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Performing database cleanup for container log timestamps
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Previous engine snapshot was not stored. Skipping cleanup.
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Handling of local mode switch is completed
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Connectivity check enabled: true
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Starting periodic check for IP addresses
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Reporting initial state, supervisor version and API info
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Skipping preloading
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Starting API server
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Supervisor API successfully started on port 48484
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   VPN status path exists.
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Applying target state
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Waiting for connectivity...
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [debug]   Ensuring device is provisioned
Jul 13 08:58:34 2a43cdb resin-supervisor[2066]: [info]    Reporting initial configuration
Jul 13 08:58:35 2a43cdb resin-supervisor[2066]: [debug]   Finished applying target state
Jul 13 08:58:35 2a43cdb resin-supervisor[2066]: [success] Device state apply success
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]   Error reporting initial configuration, will retry StatusError: Unauthorized
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]         at PinejsClientRequest._request (/usr/src/app/dist/app.js:6:509908)
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialEnv (/usr/src/app/dist/app.js:6:9344)
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9619)
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.start (/usr/src/app/dist/app.js:6:1782)
Jul 13 08:58:38 2a43cdb resin-supervisor[2066]: [error]       at async Supervisor.init (/usr/src/app/dist/app.js:2:1770522)
Jul 13 08:58:44 2a43cdb resin-supervisor[2066]: [info]    Internet Connectivity: OK
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]   Error reporting initial configuration, will retry StatusError: "device" and "name" must be unique.
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]         at PinejsClientRequest._request (/usr/src/app/dist/app.js:6:509908)
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialEnv (/usr/src/app/dist/app.js:6:9344)
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9619)
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.start (/usr/src/app/dist/app.js:6:1782)
Jul 13 08:59:09 2a43cdb resin-supervisor[2066]: [error]       at async Supervisor.init (/usr/src/app/dist/app.js:2:1770522)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]   Error reporting initial configuration, will retry StatusError: "device" and "name" must be unique.
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]         at PinejsClientRequest._request (/usr/src/app/dist/app.js:6:509908)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialEnv (/usr/src/app/dist/app.js:6:9344)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9619)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.start (/usr/src/app/dist/app.js:6:1782)
Jul 13 08:59:39 2a43cdb resin-supervisor[2066]: [error]       at async Supervisor.init (/usr/src/app/dist/app.js:2:1770522)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]   Error reporting initial configuration, will retry StatusError: Unauthorized
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]         at PinejsClientRequest._request (/usr/src/app/dist/app.js:6:509908)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialEnv (/usr/src/app/dist/app.js:6:9344)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9619)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.start (/usr/src/app/dist/app.js:6:1782)
Jul 13 09:00:10 2a43cdb resin-supervisor[2066]: [error]       at async Supervisor.init (/usr/src/app/dist/app.js:2:1770522)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]   Error reporting initial configuration, will retry StatusError: "device" and "name" must be unique.
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]         at PinejsClientRequest._request (/usr/src/app/dist/app.js:6:509908)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialEnv (/usr/src/app/dist/app.js:6:9344)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9619)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.reportInitialConfig (/usr/src/app/dist/app.js:6:9817)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]       at async APIBinder.start (/usr/src/app/dist/app.js:6:1782)
Jul 13 09:00:41 2a43cdb resin-supervisor[2066]: [error]       at async Supervisor.init (/usr/src/app/dist/app.js:2:1770522)
Jul 13 09:01:11 2a43cdb resin-supervisor[2066]: [error]   Error reporting initial configuration, will retry StatusError: "device" and "name" must be unique.

**Comment by floion** [comment]
This bug also appeared on a rpi4 at version 2.52.7+rev1 running preloaded resin-wifi-connect

**Comment by floion** [comment]
Reproduced in now times in a row.

Steps I took:

1 - Created an app in production for rpi4 and pushed github.com/balena-io/wifi-connect to that app.
2 - Downloaded rpi4 at version 2.52.7+rev1 from staging and preloaded the image with the wifi connect app I pushed at step 1.
3 - Burned to SD card the resulting image from step 2.
4 - Downloaded from the UI the config.json for the app I created in step 1.
5 - Mounted the first partition of the SD card I burnt at step 3 and overwrote the existing config.json there with the one I downloaded at step 4.
6 - Unmounted the SD card and booted my rpi4 with it.

**Comment by floion** [comment]
Same problem with `2.53.9+rev1` from staging and running the above steps. This is 100% reproducible for me.

**Comment by CameronDiver** [comment]
Thanks for the report @floion 

Looking at the code, it appears to me that this is due to the target state not being available when we try to report our initial configuration. This causes the supervisor to think that it can report every piece of configuration which is a default in a given OS. 

I see three ways forward for this issue:
1. We first try to post the configuration values we have and if that fails, we try to patch. If that fails we don't stop the supervisor boot/provision process and instead report it in the dashboard and continue. The downside of this is that if the user has set a application configuration value, it would be overwritten by the device provision for this specific device.
2. We try to post the configuration value, and if that fails, ignore the error and continue for the remaining configuration. We don't let a configuration value write error stop the normal boot. This has the disadvantage that some OS specific configuration could be lost.
3. We wait for a target state to be fetched before attempting to report our initial configuration. This provides the same behaviour that we have now, but means that the initial configuration potentially could not be written if the device goes offline post-provision but before getting a target state. This is an issue we have now though, but the proposed change could exacerbate it.

@Page- @richbayliss @20k-ultra let me know your thoughts here.
