### ISSUE TITLE
The value for BALENA_SUPERVISOR_HOST is incorrect in containers

### ISSUE THREAD

**Issue by richbayliss** [balena-io/balena-supervisor#1401]
Possible bug here: https://github.com/balena-io/balena-supervisor/blob/aad20e2c2f9bf62dfb2e3092d898b100f911ecc5/src/lib/docker-utils.ts#L237

I suspect the change to singletons means that this should be `docker.getNetwork` instead of `this.getNetwork`.

**Comment by 20k-ultra** [comment]
There are 2 other places that uses `this` to reference functions (getImage and fetchImageWithProgress).
