### ISSUE TITLE
Power cycling device corrupts container state

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1413]
While doing some reboot testing, some of the containers on a user's device did not start up again. The user was performing hard reboots by cutting power or forcing the device (intel nuc) to power off right away. This is different then issuing a graceful shutdown because there is not time for the Supervisor to perform whatever stopping/cleaning of containers is required.

Containers will begin to resume again after a soft-reboot but we should figure out what causes containers that were previously running to not run after power loss. It might take a few hard reboots to create the correct conditions.

**Comment by 20k-ultra** [comment]
There are many strategies we can try to implement to mitigate this issue but ultimately it's not a Supervisor specific issue as data corruption can happen to any service on the device. I'll leave this issue open just to help document ways we can 100% reproduce corrupt states from power loss and if there are any strategies we can try to fix them.

**Comment by CameronDiver** [comment]
Closing as there's nothing really to do here.
