### ISSUE TITLE
Retrieve of device tags not working as documented

### ISSUE THREAD

**Issue by kimkil94** [balena-io/balena-supervisor#1453]
Hello,

from supervisor v10.11.2 retrieving device tags is not working like is stated in documentation.
https://www.balena.io/docs/reference/supervisor/supervisor-api/#device-tags

`root@venue122:~# curl --silent "$BALENA_SUPERVISOR_ADDRESS/v2/device/tags?apikey=$BALENA_SUPERVISOR_API_KEY"'
{"status":"failed","message":"Cannot read property 'map' of undefined"}`

on v10.11.1 is working as expected/documented.
`root@venue122:/# curl --silent "$BALENA_SUPERVISOR_ADDRESS/v2/device/tags?apikey=$BALENA_SUPERVISOR_API_KEY"
{"status":"success","tags":[{"id":144,"name":"monitoring","value":"1"}]}`

I see in changelog, that there was some change regarding to retrieving tags. Could you please  help me and update documentation if there is something outdated?

Thank you in advance :)

**Comment by kimkil94** [comment]
On latest version (v11.14.0) is not working as well, with different response.
`# curl --silent "$BALENA_SUPERVISOR_ADDRESS/v2/device/tags?apikey=$BALENA_SUPERVISOR_API_KEY"
{"status":"failed","message":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /v6/device_tag</pre>\n</body>\n</html>\n"}`

**Comment by 20k-ultra** [comment]
Thanks for reporting this issue @kimkil94. I just tried this on my own device running `v11.14.0` and it correctly returned the tags I have set on the dashboard. I'll keep poking around to see what I can find that would explain the messages you got. Are you experiencing this on any other devices ?

**Comment by kimkil94** [comment]
> Thanks for reporting this issue @kimkil94. I just tried this on my own device running `v11.14.0` and it correctly returned the tags I have set on the dashboard. I'll keep poking around to see what I can find that would explain the messages you got. Are you experiencing this on any other devices ?

Hi there,
I've tried only on several devices all are rasperrypi3. I forgot to mention, that I'm using openbalena. I set tags via API only.

**Comment by 20k-ultra** [comment]
Thanks for the additional info. I'll setup a device with openBalena and confirm if I experience the same issue.

**Comment by 20k-ultra** [comment]
Hey @kimkil94, sorry for the wait just for me to say that unfortunately right now Supervisor v10.11.2 and up are not compatible with your version of openBalena right now. We have 2 issues in the open-balena-api and open-balena repos to track this. We aren't able to make any changes on the Supervisors end to resolve this.

See https://github.com/balena-io/open-balena/issues/80 and https://github.com/balena-io/open-balena-api/issues/388.
