### ISSUE TITLE
Force update via supervisor API not working

### ISSUE THREAD

**Issue by kimkil94** [balena-io/balena-supervisor#1454]
Hello,

I’m experiencing problem with overriding update lock using supervisor API directly or via API Proxy  and force update.
It works on older version of supervisor that we use (**11.0.0**) and **balenaOS 2.43.0+rev1..**
After upgrading version of supervisor API (we need newer version for new features) is not working.
Latest version that we tried was **11.14.0** with no effect as well.

Only working solution for now, is setting up config variable **BALENA_SUPERVISOR_OVERRIDE_LOCK**, but it's not very suitable for our use case. (we want to trigger update from container using supervisor API)

We are using self-hosted openbalena.

Steps to reproduce
Reproduced on **raspberrypi3** with supervisor version **11.14.0** and **balenaOS 2.53.9+rev1**

 Check if there is no update waiting.
`curl -X POST -H "Content-Type:application/json"     -H "Authorization: Bearer XXXXYYYYZZZZZ"     --data '{"uuid": "DEVICE_UUID", "method": "GET"}'     "https://api.balena.xxxyyyzzz.com/supervisor/v1/device"
{"api_port":48484,"ip_address":"192.168.1.10","os_version":"balenaOS 2.53.9+rev1","mac_address":"B8:27:EB:3F:7E:07 0A:C7:DC:E0:F0:52","supervisor_version":"11.14.0","update_pending":false,"update_failed":false,"update_downloaded":false,"commit":"462c1b17daa020cdb51a1989085b7285","status":"Idle","download_progress":null}`

For demonstration I'm changing only env variable to trigger update process.

Now there is update pending
`curl -X POST -H "Content-Type:application/json"     -H "Authorization: Bearer XXXXYYYYZZZZZ"     --data '{"uuid": "DEVICE_UUID", "method": "GET"}'     "https://api.balena.xxxyyyzzz.com/supervisor/v1/device"
{"api_port":48484,"ip_address":"192.168.1.10","os_version":"balenaOS 2.53.9+rev1","mac_address":"B8:27:EB:3F:7E:07 0A:C7:DC:E0:F0:52","supervisor_version":"11.14.0","update_pending":true,"update_failed":true,"update_downloaded":false,"status":"Idle","download_progress":null}`

Logs from resin_supervisor, as expected updates are locked
```
[debug]   Replacing container for service cron because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[debug]   Replacing container for service node-exporter because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[debug]   Replacing container for service wifi-connect because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[debug]   Replacing container for service startup because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[info]    Updates are locked, retrying in 16s...
```

Now I am calling force update via Proxy API.

`curl -X POST -H "Content-Type:application/json"     -H "Authorization: Bearer XXXXYYYYZZZZZ"     --data '{"uuid": "DEVICE_UUID", "data": {"force": true}}'     "https://api.balena.xxxyyyzzz.com/supervisor/v1/update"`

Logs from supervisor
```
[event]   Event: Update notification {}
[api]     POST /v1/update 204 - 67.215 ms
```

Nothing will happen. Updates are locked message keeps showing.
```
[debug]   Replacing container for service node-exporter because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[debug]   Replacing container for service wifi-connect because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[debug]   Replacing container for service startup because of config changes:
[debug]     Non-array fields:  {"added":{},"deleted":{},"updated":{"environment":{"local_songs_limit":"1700"}}}
[info]    Updates are locked, retrying in 4m...
```

If BALENA_SUPERVISOR_OVERRIDE_LOCK config variable is used, its working like a charm.

Are there any changes in newer versions that are not mentioned in documentation or am I doing something wrong? Anyone experiencing similar problem?

**Comment by 20k-ultra** [comment]
Hey @kimkil94 thanks for the super detailed issue with steps to reproduce the issue, this is very helpful. I'll setup an openBalena device soon and try this out.

**Comment by 20k-ultra** [comment]
hey @kimkil94 I'm sorry for the delay just to say that this issue is not resolvable from the Supervisor end. Unfortunately your openBalena version is not compatible with this version of the Supervisor and we have https://github.com/balena-io/open-balena/issues/80 tracking this issue.
