### ISSUE TITLE
Does not always reboot device with fleet custom configuration variables

### ISSUE THREAD

**Issue by majorz** [balena-io/balena-supervisor#1455]
Supervisor does not always reboot a device when it is provisioned for the first time with custom configuration variables applied to the whole fleet. Steps that I used to reproduce (in sync with the customer's use-case):

1. Create a new application for with a RPi 4 device type
2. Define the following variables fleet-wise
```
BALENA_HOST_CONFIG_gpu_mem_1024 = 448
BALENA_HOST_CONFIG_gpu_mem_256 = 192
BALENA_HOST_CONFIG_gpu_mem_512 = 256
RESIN_HOST_CONFIG_start_x = 1
```
3. Flash an SD card with an OS image for this application
4. Power up the device
5. The device is not rebooted on first boot although config.txt does contain the necessary definitions written by supervisor.

I needed like 8 attempts to reproduce this, so it does not happen each time.

Useful command to see whether the changes were applied is `vcgencmd get_mem gpu` which gives `gpu=448M` if all worked correctly, or `gpu=16M` if not. The dashboard logs are also a good indication of whether the device was rebooted.

**Comment by pipex** [comment]
@majorz hey Zahari, did you by any chance happen to note the supervisor version for this issue?

**Comment by hnnsgstfssn** [comment]
I've seen this reproduced on at least v11.4.10 and v11.9.9, @pipex.
