### ISSUE TITLE
Inconsistent memory reporting for node containers

### ISSUE THREAD

**Issue by pipex** [balena-io/balena-supervisor#1471]
When running node containers, dashboard RAM usage shows a different value that what is reported by the 
`top` and `balena stats` commands. 

In a [reported case](https://www.flowdock.com/app/rulemotion/r-supervisor/threads/UvX4-J4fQkvosmG_SkGtlvLN5eH) for a rpi3, the dashboard and  the `free` command show 700MB in use, while `top` and `balena stats` show 200MB usage. 

This requires further investigation to find the source of truth of memory usage and report the correct value to the user.

**Comment by 20k-ultra** [comment]
A user has provided a description of what seems to be the current cause of this issue.

```
The new added dashboard widget is giving wrong information, the memory usage doesn't take into account memory used for cache, giving a false impression that the device is running out of memory when in reality linux tries to use as much memory as possible for cache that can be take into account as free memory, ie. you can check how htop displays the memory usage. Then the disk usage one, at least in one device, is showing 2.8G of 2.8G used and if we look at df in the device, we can see that 1.6G is free.
```

@xginn8 looked into how we are retrieving the memory usage of the device and had the following to say:

```
In terms of memory usage, the supervisor uses a module called systeminformation which in turn calculates used memory as totalmem - freemem from /proc/meminfo (seen here: https://github.com/sebhildebrandt/systeminformation/blob/master/lib/memory.js#L154).
```

Therefore, we should see if this module is calculating with the cached memory.

**Comment by xginn8** [comment]
This is pretty well outlined in the kernel manpage: https://man7.org/linux/man-pages/man5/proc.5.html
