### ISSUE TITLE
Stop fetching device-type from config.json

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#1472]
We should instead use the device-type.json. We use this file here https://github.com/balena-io/balena-supervisor/blob/master/src/config/functions.ts#L43 for the device architecture, and we should also fetch the device-type from there. 

We should use the `BOOT_MOUNTPOINT` supervisor variable to access the file in addition.

**Comment by 20k-ultra** [comment]
The device-type is populate from config.json in [provisioningOptions](https://github.com/balena-io/balena-supervisor/blob/7ca1f837ff98990435333488f8312965420c0f34/src/config/functions.ts#L65) and [extendedEnvOptions](https://github.com/balena-io/balena-supervisor/blob/7ca1f837ff98990435333488f8312965420c0f34/src/config/functions.ts#L104). Also device architecture has its own function that you provided but in the above 2 functions I just linked they also provide a deviceArch value which pulls from config.json.

Should we make all references to deviceType and deviceArch be pulled from device-type.json ?

**Comment by 20k-ultra** [comment]
There's no test coverage for this file so we should make them when we make this change.

**Comment by CameronDiver** [comment]
@20k-ultra yeah all references to deviceType and deviceArch should come from device-type.Jason
