### ISSUE TITLE
Temperature reported to dashboard seems to stop updating.

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-supervisor#1481]
I have noticed a few devices in the past few days that seem to not update their temperature values. From what I can see it seems the value stays at what the supervisor first reads when starting up. I had a device that on the dashboard indicated that it was 49C but running `cat /sys/class/thermal/thermal_zone0/temp` showed 72C later in the day (it was sitting in the sun). When I restarted the supervisor it correctly showed the 72C.

**Comment by CameronDiver** [comment]
@shaunmulligan do you happen to have the supervisor logs from when this happened? I'll setup a device and keep monitoring but that would be helpful.

**Comment by CameronDiver** [comment]
Fixed here: https://github.com/balena-io/balena-supervisor/pull/1484
