### ISSUE TITLE
'io.balena.features.balena-socket' label not creating volume for Intel Nuc

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1494]
If you add 'io.balena.features.balena-socket' label to your service in most device the balena engine socket will be mounted as a volume inside the service. This still works on the latest versions for rpi4 but it has been reported for broken for the following versions on Intel Nuc:
 - 2.44.0+rev1 with Supervisor 10.3.7
 - 2.50.1+rev1 with Supervisor 11.4.10

This is on the same device that was updated to try and fix but did not.

We confirmed this issue exists by checking if the socket is in `/var/run` within the service.

**Comment by ab77** [comment]
Running `systemd` in the container breaks `balena-engine.socket` bind mount. To replicate, deploy https://github.com/balena-io-examples/balenalib-systemd-example to a device with updated `docker-compose.yml` mapping balena-engine socket.
