### ISSUE TITLE
/v2/.../start-service API endpoint throws exception if lock exists

### ISSUE THREAD

**Issue by pipex** [balena-io/balena-supervisor#1523]
If a lock is left after a service crash, `/v2/applications/:appId/start-service` will fail with the error `UnhandledPromiseRejectionWarning: UpdatesLockedError: Updates are locked: EEXIST: file already exists, open '/mnt/root/tmp/balena-supervisor/services/1680126/hello-world/updates.lock'`

This is a probably a bug, since a lock should not prevent the start of a service (as a restart does)

Steps for replication

1. Install any service on a device such as https://github.com/balena-io-examples/balena-node-hello-world
2. SSH into the service and create a [lockfile](https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/#application-update-locks) in `/tmp/balena/updates.lock`
3. Simulate a service crash with `balena stop <containerId>`
4. Check that the dashboard service state is updated, it should report `Exited` as state for the service.
5. Click on the start button for the service. The journal will report the error above

The workaround for now is enabling lock overrides and retrying.

**Comment by 20k-ultra** [comment]
fixed in 12.4.10
