### ISSUE TITLE
Multiple services stuck on status Downloaded & not running

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-io/balena-supervisor#1612]
Supervisor version: 12.3.5

Encountered an issue on support where services were getting downloaded or shown as status `Downloaded` on the dashboard but not `Running`. Happened to multiple devices (3) across different applications (2 apps with the same codebase). No error messages from engine or the supervisor, no issues on healthchecks, nothing out of the ordinary except on one of the devices the supervisor status was shown as `Idle` even when the services got downloaded but didn't run.  

At the moment, a supervisor restart with `systemctl restart supervisor` fixed it as a workaround to the problem. Linking the thread below with full logs and all the context saved. I have added some summary messages that might be helpful for context @pdcastro mentions of seeing this issue once in 11.14.0 as well

**Comment by 20k-ultra** [comment]
This issue is probably the most generic one that exists for the Supervisor "why didn't my containers start". Not your fault just saying as these are incredibly hard to debug without access to a device that is in the broken state... hopefully I can get access to a device with this issue.

**Comment by vipulgupta2048** [comment]
Hey @20k-ultra Yes, I know right. Out of the 3 devices, 2 recovered. Hopefully, you can reach out to the 3rd device still in the broken state and can debug the issue. If the customer hasn't already fixed it with the workaround.

**Comment by 20k-ultra** [comment]
Closing in favor of https://github.com/balena-io/balena-supervisor/issues/1618 because the 2 tickets attached are for that issue and I want to prevent people using this issue for further issue tracking since it is too general.
