### ISSUE TITLE
Harden registry authentication

### ISSUE THREAD

**Issue by afitzek** [balena-io/balena-supervisor#414]
Rewrite the client authentication for the registry v2 to query the API and retrieve an access token for the registry, before calling docker pull. The retrieved token is then handed over to docker using "registrytoken" option. (https://docs.docker.com/engine/api/v1.22/#images)

**Comment by afitzek** [comment]
We should also use the Authorization header when https://github.com/resin-io/hq/pull/370 is available.

**Comment by pcarranzav** [comment]
@afitzek is this still an issue? The use Authorization header was definitely added in #482 - but authentication with the registry is done by using the deviceApiKey (which I think makes the call to the resin API to get a token happen inside docker/balena?)
