### ISSUE TITLE
When going out of local mode, the supervisor doesn't delete containers created in local mode

### ISSUE THREAD

**Issue by pcarranzav** [balena-io/balena-supervisor#681]
This happened with the changes in 7.x where we stopped cleaning up all external containers.

This will likely require a change in the CLI to add a specific label to local mode containers (e.g. io.resin.supervised) and some changes in the supervisor to detect these as local mode containers and remove them going out of local mode.

Probably better to make it part of the multicontainer local mode changes, but could also be done before to fix this particular issue...

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c78r)

**Comment by CameronDiver** [comment]
With new mode local mode, this doesn't occur.
