### ISSUE TITLE
Device rebooting due to (presumably) a corrupted delta, needs investigation

### ISSUE THREAD

**Issue by flesler** [balena-io/balena-supervisor#718]
cc @CameronDiver

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_d3wb)

**Comment by CameronDiver** [comment]
Never been seen to happen again, so it was either fixed, or the problem was elsewhere. Closing unless we get a more detailed issue description.
