### ISSUE TITLE
Pinning preloaded images for the flasher type does not work

### ISSUE THREAD

**Issue by telphan** [balena-io/balena-supervisor#725]
The pinning has to happen during the supervisor's provision of the device.
But the flasher provisions (in the supervisor way) the device without the supervisor, resulting in the pinning never happening when we start the supervisor.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ddcr)

**Comment by CameronDiver** [comment]
Can this be closed @telphan ?
