### ISSUE TITLE
Device state report failures have an empty error message

### ISSUE THREAD

**Issue by Page-** [balena-io/balena-supervisor#827]
eg
```
Event: Device state report failure {"error":{"message":""}}
```

One known cause is if the device has the incorrect time, not sure if there are others

**Comment by pdcastro** [comment]
A customer reported several devices in the past 48 hours (the ones I saw were running balenaOS 2.29.2+rev1, supervisor 9.0.1) showing this error message in supervisor logs:
```
$ journalctl -au resin-supervisor --no-pager
...
Jun 13 18:41:48 902f8f0 resin-supervisor[965]: [2019-06-13T18:41:47.927Z] Event: Device state report failure {"error":{"message":""}}
Jun 13 18:42:49 902f8f0 resin-supervisor[965]: [2019-06-13T18:42:49.098Z] Event: Device state report failure {"error":{"message":""}}
Jun 13 18:43:51 902f8f0 resin-supervisor[965]: [2019-06-13T18:43:51.046Z] Event: Device state report failure {"error":{"message":""}}
Jun 13 18:44:53 902f8f0 resin-supervisor[965]: [2019-06-13T18:44:53.086Z] Event: Device state report failure {"error":{"message":""}}
Jun 13 18:45:54 902f8f0 resin-supervisor[965]: [2019-06-13T18:45:54.264Z] Event: Device state report failure {"error":{"message":""}}
```
This would prevent the device from updating app images to a new release. Some devices appeared to have eventually recovered by themselves, others were recovered by taking the following action:
```
$ systemctl stop resin-supervisor
$ balena images -a
# take note of the image IDs of all images other than the supervisor's image
$ balena rmi imageID1 imageID2 ...
$ systemctl stop balena
$ systemctl start balena
$ systemctl start resin-supervisor
```
I suspect that restarting balenaEngine wasn't really necessary; my best guess is that the key was to delete the old images. In one of the devices (I think only one of them), the customer reported that issue happened after the device was moved to a different application while the device was offline.

**Comment by pdcastro** [comment]
In one of the devices, Shaun spotted this error in logs:
```
msg="failed to download layer: \"read tcp 10.254.44.46:34208->52.216.107.108:443: read: connection reset by peer\", retrying to read again"
```
But in the device I was looking into, I didn't see that error. Then again, the user had rebooted the device I was looking into shortly before my investigation.

**Comment by pdcastro** [comment]
In another data point, @xginn8 also observed this error today with balenaOS 2.32.0+rev4, supervisor 9.14.0 ("NUC VM with loads of other issues, so don't necessarily read too far"; in a different guess, maybe "it's associated with exhausting a connection pool, or hitting open filehandle limits").

**Comment by CameronDiver** [comment]
Closed by https://github.com/balena-io/balena-supervisor/pull/995
