### ISSUE TITLE
Migrations can run without the knex_migrations table being updated, causing duplicate column name errors

### ISSUE THREAD

**Issue by pcarranzav** [balena-io/balena-supervisor#838]
This seems to be a consequence of how knex 0.12.x runs migrations: https://github.com/tgriesser/knex/blob/0.12.9/src/migrate/index.js#L332 - note that it runs the migration in the transaction, and updates the knex_migrations *outside* the transaction.

This seems to be fixed in newer knex versions, that wrap *all* migrations inside a big transaction (as long as no migrations try to disable transactions): https://github.com/tgriesser/knex/blob/0.16.0/src/migrate/Migrator.js#L360

The symptom that we saw for this was a device where the supervisor couldn't start because of a duplicate column name error: 

```
Dec 06 20:04:00 53ed1e7 resin-supervisor[4522]: resin_supervisor
Dec 06 20:04:00 53ed1e7 resin-supervisor[4582]: active
Dec 06 20:04:00 53ed1e7 systemd[1]: Started Resin supervisor.
Dec 06 20:04:01 53ed1e7 resin-supervisor[4583]: Removing stale PID file /var/run/messagebus.pid.
Dec 06 20:04:01 53ed1e7 resin-supervisor[4583]: Starting system message bus: dbus.
Dec 06 20:04:01 53ed1e7 resin-supervisor[4583]:  * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
Dec 06 20:04:01 53ed1e7 resin-supervisor[4583]:    ...done.
Dec 06 20:04:06 53ed1e7 resin-supervisor[4583]: [2018-12-06T20:04:06.667Z] Knex:warning - migrations failed with error: alter table "image" add column "dockerImageId" varchar(255) - SQLITE_ERROR: duplicate column name: dockerImageId
Dec 06 20:04:06 53ed1e7 resin-supervisor[4583]: [2018-12-06T20:04:06.730Z] Unhandled rejection Error: alter table "image" add column "dockerImageId" varchar(255) - SQLITE_ERROR: duplicate column name: dockerImageId
Dec 06 20:04:06 53ed1e7 resin-supervisor[4583]:     at Error (native)
```

In this case, the migration that adds dockerImageId had run, but this wasn't reflected in knex_migrations:

```
sqlite> select * from knex_migrations;
1|20171129013519_legacy.js|1|1544055434266
2|20171129064057_multicontainer.js|1|1544055434840
```

So I fixed it by manually adding the entry in knex_migrations:

```
balena exec -ti resin_supervisor node
```

and then inside this node terminal:

```
var sqlite = require('sqlite3')
db = new sqlite.Database('/data/database.sqlite')
db.run("insert into knex_migrations (name, batch, migration_time) values ('20171214172530_image_docker_id.js', 1, 1544055434841);")
```

We could in theory hit this for different migrations, so fixing this on a particular device will require looking at what migration was the last one to run, and what was the last one that was inserted into knex_migrations.

The actual fix for the root cause of the issue would be to update knex to the latest version (which should be done with care, since there's a relationship between knex and sqlite3, which is the only module that needs to be installed external to webpack).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fwe3)

**Comment by CameronDiver** [comment]
Closed by https://github.com/balena-io/balena-supervisor/pull/817
