### ISSUE TITLE
Healtheck logic changes

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-supervisor#843]
We want to not mark the healthcheck as unhealthy if we recieve any http status back from the api - this means that something about the data is wrong, but the connectivity is not.

[Arch call](https://app.frontapp.com/open/cnv_14sprkr)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fz7f)

**Comment by shaunmulligan** [comment]
@CameronDiver did we make the healthcheck improvements for this issue yet?

**Comment by CameronDiver** [comment]
Closed by https://github.com/balena-io/balena-supervisor/pull/902
