### ISSUE TITLE
exposing the API endpoint as a variable to the user containers

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-supervisor#847]
Expose the API endpoint as a variable to the user containers in those ones that already have `io.balena.features.balena-api` Currently one cannot write code that works across balena deployments, as it's not sure what endpoint to call (ie `api.balena-cloud.com` or `api.balena-staging.com`). This should be even more relevant now that we have devices join and leave deployments, the same deployed code should work across them.

**Comment by richbayliss** [comment]
I also would like this feature.

**Comment by richbayliss** [comment]
@imrehg I have resolved this.
