### ISSUE TITLE
Support the service: <name> option for network_mode

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#851]
Users would like to assign a network mode for a service to another service.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g5bf)

**Comment by edkeeble** [comment]
Hi @CameronDiver,

We are very interested in this feature. I would be happy to take a crack at it, if you can point me in the right direction, as I haven't worked on supervisor before and have just taken a quick initial look. I see where these values are being filtered out in service.ts, but haven't yet figured out where they are used following that.

Thanks!

**Comment by CameronDiver** [comment]
Hey @edkeeble thanks for the interest!

I'll try to outline the steps necessary for this to be implemented;

Firstly, this causes an implicit dependency between the services, as a service `a` having a `network_mode` of `service: b`, would require that `b` is running, so that we can convert the service name to the container id, which would be required by docker (https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate). To do this we would have to add a `depends_on` entry, in the service configuration.

The next issues arises when comparing the current and target state of the container with a `service:` network mode. We'd have to convert the service name to a container id, to ensure that if the depended on service gets recreated, we will recreate the service with a service with a `service:` network mode. This could also create a deadlock if done improperly, so it's something to watch out for.

There may be other things which come up because of it too, so all in all it's not a small (or simple) change. 

What is the reason that you would like to use this feature? Would it be possible to use a private network instead?

I'll be away for a week or two, but can try to prioritise this feature when I get back if you prefer.

**Comment by edkeeble** [comment]
Thanks for the explanation, Cameron.

In our case, we're supporting a legacy application which needs to route traffic from/to our cloud services to/from specific containers on our edge device through an openvpn container (streaming video from the device, for instance). We actually have a workaround setup, using iptables on each of the relevant containers to handle the routing, but for the sake of long-term maintenance, we'd prefer to use the more typical network_mode approach.

I don't mind taking a look at it, as I'm sure I'll learn a lot about supervisor in the process, but given the level of complexity and possibility of side effects, if you would prefer I leave it to you, then we can certainly wait until you get back and have a chance to look into it.

Thanks again.

**Comment by CameronDiver** [comment]
Hey @edkeeble I managed to get to this and it should be working well for you, once an accompanying balenaOS release comes out. Please let me know if this doesn't, and sorry for the delay!

**Comment by edkeeble** [comment]
Thanks very much, @CameronDiver! We will give this a try once it's released. It should simplify things quite a bit for us, so it's much appreciated.
