### ISSUE TITLE
Extend host-config endpoint to support setting udev rules

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-supervisor#880]
It's possible to specify custom udev rules through config.json:
https://github.com/balena-os/meta-balena/blob/master/README.md#udevrules

However, some users need the ability of modifying those rules at runtime (even if a reboot is required for the changes to take effect). It sounds like extending the supervisor's [/v1/device/host-config](https://www.balena.io/docs/reference/supervisor/supervisor-api/#patch-v1-device-host-config) API endpoint to allow setting the custom udev rules would be a clean way of achieving that.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gw6j)

**Comment by pdcastro** [comment]
Related to pull request: balena-os/meta-balena/pull/1206

**Comment by pdcastro** [comment]
Related to issue: https://github.com/balena-io/balena/issues/886

**Comment by tlangmo** [comment]
Hi. To elaborate on the feature request...
We are plugging in our own hardware in to the balena device via USB. All our hardware exposes the USB ACM Device class and such shows up looking similar to a serial modem. When ModemManager is active, it starts probing our hardware for about 30 seconds by sending bytes to it, which causes data corruption in our communication stream. 

Having custom udev rules for our hardware (filtered by vendorId, productId etc) would work, but it is not practical to set those up in the 'factory' - hardware will change and we also have a lot devices already in the field with this problem. So we would really appreciate if we can set those rules via the container or as a app/service configuration in the dashboard.

Thank you

**Comment by CameronDiver** [comment]
Closed by https://github.com/balena-io/balena-supervisor/issues/998
