### ISSUE TITLE
When the device type is fincm3, the supervisor should not delete the balena-fin dtoverlay

### ISSUE THREAD

**Issue by pcarranzav** [balena-io/balena-supervisor#884]
On balena fin devices (i.e. deviceType is fincm3), there is a `dtoverlay=balena-fin` entry that comes by default in config.txt. This device tree overlay configures several hardware peripherals required for the board to function.

With the current way the supervisor works, if a user sets a fleet-wide value for the BALENA_HOST_CONFIG_dtoverlay variable, they may overwrite the balena-fin entry, causing the device to be unable to come online again.

Since the balena-fin entry is required for fin devices, if the deviceType is fincm3, the supervisor should always append a "balena-fin" entry to whatever value is set for dtoverlay in the target state.

**Comment by CameronDiver** [comment]
@pcarranzav could you add a description to this please? I wasn't around for the initial discussion, so I'm not exactly clear on what is going on.
