### ISSUE TITLE
The supervisor should report tags and other metadata via supervisor API

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#890]
Any information that is available to the dashboard about a device should be requestable from the container over supervisor API.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h3az)

**Comment by shaunmulligan** [comment]
@CameronDiver will the "other metadata" include things like `HOST_CONFIG` vars? For instance it might be nice for a container to be able to query what `dtoverlay` it has, etc.

**Comment by CameronDiver** [comment]
It can do @shaunmulligan, I've added it to the list here: https://github.com/balena-io/balena-supervisor/issues/685
