### ISSUE TITLE
Whitespace in front of the env var is causing an issue, getting containers in a restart loop

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-supervisor#895]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h5fv)

**Comment by lekkas** [comment]
The workaround is to delete the leading whitespace characters.

**Comment by CameronDiver** [comment]
Closed by: #901
