### ISSUE TITLE
Supervisor should be able to read "deviceName" from config.json for preloading

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-supervisor#909]
We should add device_name_at_init in to the config.json and the supervisor should prefer config.json name over anything in apps.json, if a user defined a `"deviceName": "myDevice"` in their config.json at preload, on first boot, the supervisor should use that name for `device_name_at_init` and for provisioning.

**Comment by trecetp** [comment]
Hi, there is any update about this?? . . . I need to set a `deviceName` to devices previously the first boot and find it after, through the `balena devices` in BalenaCLI. thanks

**Comment by CameronDiver** [comment]
Not as of yet, but I should have a bit of time in the coming week to take a look.
