### ISSUE TITLE
Docker-compose network service names not resolving correctly when `networks:` configuration is used

### ISSUE THREAD

**Issue by mikesimos** [balena-io/balena-supervisor#918]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hi43)

**Comment by CameronDiver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use service names as domain names e.g. curl http://api/test](https://trello.com/c/1GO4dlHb/55-use-service-names-as-domain-names-eg-curl-http-api-test)

**Comment by gelbal** [comment]
Thread in forums where users are waiting for the release of this fix:
https://forums.balena.io/t/docker-compose-network-service-names-not-resolving-correctly/5313/11

Please ping the thread when we release.

**Comment by OdysLam** [comment]
can we get a confirmation on whether thus update will be included in the BalenaOs64 as in [here](https://github.com/balena-os/balena-raspberrypi/issues/181)

**Comment by CameronDiver** [comment]
@OdysLam Yes this fix will be included in all device types, in balenaOS version 2.32.0

**Comment by OdysLam** [comment]
> @OdysLam Yes this fix will be included in all device types, in balenaOS version 2.32.0

Hey @CameronDiver ,

Any ETA on that version? I am asking as I am using Balena embedded in the solution for my Thesis and I would love to program vaguely when I will be back at looking to it.

Thanks for the swift response.

Cheers!

**Comment by CameronDiver** [comment]
It's currently going through internal testing, and things look good. I imagine it will be available by the end of this week or early next week, but that's not completely certain. 

If testing doesn't bring up any regressions we should be fine, but obviously, if it does those will need to be addressed first.

**Comment by OdysLam** [comment]
Amazing news, this timeline is more than accurate that I need. Thanks!

On a side note, it got my attention that `hostname` is also bugged, as although I included it in my `docker-compose.yaml` the service was unreachable using the host-name but reachable using the service name.

The new version will also fix this particular issue?

Thanks!

**Comment by CameronDiver** [comment]
Closed by https://github.com/balena-io/balena-supervisor/pull/933

**Comment by CameronDiver** [comment]
@OdysLam Sorry I missed your message. Is your container using host networking?

If so, it could be this issue: https://github.com/balena-io/balena-supervisor/issues/994
There's a workaround posted here: https://forums.balena.io/t/hostname-issues/5813
