### ISSUE TITLE
Add maintainers as codeowners

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-supervisor#926]

**Comment by CameronDiver** [comment]
Can we have @Page- @pcarranzav and myself please?

**Comment by hedss** [comment]
@CameronDiver Yep, you were all going in there anyway. :)

**Comment by Page-** [comment]
I think the only place I escape is on the ui :P

**Comment by hedss** [comment]
@Page- You and I are, unfortunately, in the top three for a load of them. This is a double edged sword...
