### ISSUE TITLE
TypeError: Cannot set value for persistentLogging, as value failed validation: ''

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-supervisor#938]
Not sure if this is really a `balena-supervisor` issue, but I'm creating this issue so we can point to it and gather more information.

Following a balenaOS upgrade from OS v2.15.1+rev2 to v2.31.0+rev1, supervisor 9.9.0 (RPi 3), the supervisor logs show the following error every 10 minutes:

```
$ journalctl -au resin-supervisor
...
Mar 16 15:01:37 5e4e1b8 resin-supervisor[2042]: [2019-03-16T15:01:37.862Z] Applying target state
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]: [2019-03-16T15:01:38.097Z] Event: Apply config change in progress {}
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]: [2019-03-16T15:01:38.107Z] Event: Apply config change error {"error":{"message":"Cannot set value for persistentLogging, as value failed validation: ''","stack":"TypeE>
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]: [2019-03-16T15:01:38.116Z] Scheduling another update attempt due to failure:  600000 TypeError: Cannot set value for persistentLogging, as value failed validation: ''
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at /usr/src/app/dist/app.js:300:129547
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at /usr/src/app/dist/app.js:9:51944
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at /usr/src/app/dist/app.js:9:27896
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at Gr (/usr/src/app/dist/app.js:9:17762)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at Function.hr.mapValues (/usr/src/app/dist/app.js:9:51916)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at t.validateConfigMap (/usr/src/app/dist/app.js:300:129277)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at /usr/src/app/dist/app.js:300:127962
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at c (/usr/src/app/dist/app.js:9:74385)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at Function.e.attempt.e.try (/usr/src/app/dist/app.js:293:142123)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at t.set (/usr/src/app/dist/app.js:300:127939)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at e.<anonymous> (/usr/src/app/dist/app.js:576:34497)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at /usr/src/app/dist/app.js:576:33760
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at Object.next (/usr/src/app/dist/app.js:576:33865)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at /usr/src/app/dist/app.js:576:32778
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at r (/usr/src/app/dist/app.js:576:32555)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]:     at Object.changeConfig (/usr/src/app/dist/app.js:576:34208)
Mar 16 15:01:38 5e4e1b8 resin-supervisor[2042]: [2019-03-16T15:01:38.117Z] Apply error TypeError: Cannot set value for persistentLogging, as value failed validation: ''
```

With the following API query, @dt-rush and @pcarranzav found that the target state value for `persistentLogging` appeared to be invalid in the database:

```
$ export DEVICEAPIKEY=$(cat /mnt/boot/config.json | jq -r .deviceApiKey)
$ export DEVICEUUID=$(cat /mnt/boot/config.json | jq -r .uuid)
$ curl https://api.balena-cloud.com/device/v2/$DEVICEUUID/state?apikey=$DEVICEAPIKEY | jq .
{
  "local": {
    "config": {
      ...
      "RESIN_SUPERVISOR_PERSISTENT_LOGGING": "",
```

Apparently the value should be `"true"` or `"false"`, but not `""`. Even if this isn't a supervisor bug, consider whether treating the empty string to mean `false` is an appropriate mitigation.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i1u3)

**Comment by pdcastro** [comment]
Update: the user who reported this issue was advised to try enabling and disabling persistent logging through the device web dashboard (device configuration tab), as a way of changing the variable value from `""` to `"false"`. Following this advice, the user reported that the problem was solved.

**Comment by CameronDiver** [comment]
I'm extremely hesistant to treat all empty strings as a falsy value, as they're very much not. Looking at the code, `persistentLogging` does have a default value, which makes me think that if the given value does not pass validation, we should fall back to the default (if one exists).

**Comment by pdcastro** [comment]
Using a default value instead of `false` is even better. 👍  I am not sure if we had an explanation for how the persistentLogging attribute was set to an empty string in the first place, but I think it makes sense to treat an empty string as "value not provided, use a default value" instead of raising a validation exception.

**Comment by LucianBuzzo** [comment]
I just saw this error hit 9 devices in production ( https://jel.ly.fish/#/79f2c2ab-be0c-4e2e-ae5e-c80ee21059ee ). Is there anything we can do to mitigate the impact of having the value set to an empty string?
