### ISSUE TITLE
The supervisor should update it's ip address on the dashboard in local mode

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#959]
Because this is useful for doing a push to device, the supervisor should update the ip address on the dashboard even in local mode, where currently the ip address stays at the value that it was when local mode was turned on.

Requested here: https://forums.balena.io/t/the-dashboard-doesnt-update-device-ips/5842/6

**Comment by roman-mazur** [comment]
@CameronDiver I'm a bit confused here.

IP address reporting is initiated with `startIPAddressUpdate`, and it does get called in local mode for me. I will test the behaviour with a real IP address change, but it may be not a supervisor issue.

**Comment by roman-mazur** [comment]
Ok, I found it. The IP address change is detected by the supervisor, but the API call to update the state is not made in local mode.
