### ISSUE TITLE
App restart loop in balenaOS 2.32.0+rev2 when overlapping expose / ports instructions are used

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-supervisor#970]
When an `EXPOSE` instruction is used in a `Dockerfile`, and an overlapping `expose` or `ports` instruction is also used in the `docker-compose.yml` file, the supervisor will restart the app container in a loop.

The temporary workaround is to remove the overlapping setting from either the `Dockerfile` or the `docker-compose.yml` file.

**The supervisor fix has already been [merged in this pull request](https://github.com/balena-io/balena-supervisor/pull/964), but this issue was created so we can point to it in forums/support until a new balenaOS release including the fix is released to production.**

**Comment by pdcastro** [comment]
**25 Apr 2019 update:** the supervisor version containing the fix is being merged into the OS. It will then go through testing and the release process for individual device types. The process is expected to take a couple of weeks.

**Comment by imrehg** [comment]
This was fixed in supervisor v9.14.4 #964 
(cc @shaunmulligan )

**Comment by imrehg** [comment]
@shaunmulligan hm, didn't see your comment in Jellyfish yet, just mentioning that this shouldn't really be an open issue anymore, IMHO, it should be a support issue (how to diagfose in situ) and maybe fix in balenaOS to pull in newer supervisor?)

**Comment by shaunmulligan** [comment]
@imrehg yeah i have created a corresponding support issue in JF, which is what I thought I was commenting on :P

**Comment by pdcastro** [comment]
I see in the [meta-balena Changelog](https://github.com/balena-os/meta-balena/blob/master/CHANGELOG.md) that balenaOS v2.33.0 includes the fixed supervisor, so it's now a matter of that OS version becoming available in production.
