### ISSUE TITLE
On leaving local mode the supervisor should clean up dangling images

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-supervisor#993]
This would be equivalent to doing
```
balena rmi $(balena images -f "dangling=true" -q)
```

Given that these images are dangling, it shouldn't interact with any normal usage of the device.

**Comment by roman-mazur** [comment]
@CameronDiver Does it make sense to also take care of unused networks and volumes?

We could use `/prune` APIs of the engine (if our version is based on something later than 1.25).
https://docs.docker.com/engine/api/v1.25/#operation/ImagePrune

Similar APIs exist for volumes and networks, and, to my understanding, are used by `docker system prune` command:
https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by CameronDiver** [comment]
We would need to test that they remove only what we want them to remove, but in general, yeah we could do that. I'm pretty sure that our balena-engine is based on > 1.25.

**Comment by roman-mazur** [comment]
Checked on BoB: API version is 1.35

**Comment by roman-mazur** [comment]
Reproduced this with [hello rust project](https://github.com/balena-io-projects/balena-rust-hello-world) (which has a multistage build).

In case of this project, `balena push <ip>` created `local_image_main` image (for the main service to run) and 2 dangling images (which should map to `builder` and `dependencies` images from the multistage build described in the project Dockerfile).

```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
<none>                              <none>              6b104f6621d6        11 minutes ago      1.26GB
local_image_main                    latest              dd97d909a94f        11 minutes ago      145MB
<none>                              <none>              f16281f6026c        11 minutes ago      1.25GB
```

The dangling images don't have `io.resin.local.image` label, so will not be removed when local mode is disabled.

**Comment by CameronDiver** [comment]
This also holds true for images that are not built on device and instead are provided using the docker-compose `image:` directive I believe.

**Comment by roman-mazur** [comment]
Yes, confirmed with the following docker-compose file:
```
version: '2'
services:
  main:
    build: .
    links:
      - "redis:redis-db"
    volumes:
      - test-volume:/var/lib/test-data
  redis:
    image: "redis:alpine"
  main2:
    build: .
    networks: 
      - test-network
networks:
  test-network:
volumes:
  test-volume:
```

Networks and volumes seem to be deleted normally as a result of services deletion when local mode is disabled.

That said, I got a bunch of volumes (90+) on my machine which origin I cannot explain. Investigating.

**Comment by roman-mazur** [comment]
Also, I have a bunch of containers running `/bin/sh -c while true; do sleep` left after deploying that docker-compose.yaml and disabling local mode later.

**Comment by CameronDiver** [comment]
@roman-mazur I believe those are created by livepush, although there is code there to remove them, so I'm not sure why they're still there on your device.

**Comment by roman-mazur** [comment]
Supervisor is attempting to remove the images
```
[debug]   Cleaning up sha256:6ca52dbba8872a633c97c75f9f40fb7eab9b1de2c2f689e17b527d08e52e9de2
[event]   Event: Image cleanup error {"error":{"message":"(HTTP code 409) conflict - conflict: unable to delete 6ca52dbba887 (cannot be forced) - image is being used by running container dcd5fe475f5d ","stack":"Error: (HTTP code 409) conflict - conflict: unable to delete 6ca52dbba887 (cannot be forced) - image is being used by running container dcd5fe475f5d \n    at /usr/src/app/dist/app.js:43665:17\n    at getCause (/usr/src/app/dist/app.js:43695:7)\n    at Modem.__dirname../node_modules/docker-modem/lib/modem.js.Modem.buildPayload (/usr/src/app/dist/app.js:43664:5)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:43640:14)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"}}
```

But it apparently does it without the force flag.
